// export const TOGGLE_TODO = "TOGGLE_TODO";
// export const ADD_TODO = "ADD_TODO";

// ADDTODO TYPE
export const ADD_TODO_REQUEST = "ADD_TODO_REQUEST"
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS"
export const ADD_TODO_FAILURE = "ADD_TODO_FAILURE"
// GETTODO TYPE
export const GET_TODO_REQUEST = "GET_TODO_REQUEST"
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS"
export const GET_TODO_FAILURE = "GET_TODO_FAILURE"
export const ADD_COUNTER = "ADD_COUNTER"
export const REDUCE_COUNTER = "REDUCE_COUNTER"
