export const GET_STUDENT_REQUEST = "GET_STUDENT_REQUEST"
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS"
export const GET_STUDENT_FAILURE = "GET_STUDENT_FAILURE"
export const REMOVE_STUDENT = "REMOVE_STUDENT"